version: '3'
services:


  dbeaver:
    # username: cbadmin
    # password: cbadmin20
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    networks:
      - docker_licenta
    ports:
      - "8978:8978"
    volumes:
      - ./dbeaver-data:/home/dbeaver


  # keycloak:
  #   image: quay.io/keycloak/keycloak:21.0.2
  #   container_name: keycloak
  #   environment:
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #   command: start-dev
  #   networks:
  #     - docker_licenta
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./Keycloak/custom-theme:/opt/keycloak/themes/custom-theme

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: licenta_db
    ports:
      - "5432:5432"
    networks:
      - docker_licenta
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data # Persist PostgreSQL data to a local directory
  
    
  redis:
    container_name: redis
    image: redis:6.0.10-alpine
    networks:
      - docker_licenta
    ports:
      - "6379:6379"


  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    networks:
      - docker_licenta
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    depends_on:
      - zookeeper
    networks:
      - docker_licenta
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,CONNECTIONS_FROM_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - /var/lib/kafka/data


networks:
  docker_licenta:
    external: true


