namespace Components.UI.Enums
{
    public enum IconName
    {
        None,
        FileUpload,
        Times,
        QuestionCircle,
        FileDownload,
        MinusCircle,
        Add,
        Check,
        Thrash,
        ThrashCan,
        UserCircle,
        FileSignature,
        Image,
        File,
        Eye,
        Ban,
        CaretDown,
        CaretRight,
        Caretleft,
        Forward,
        Backward,
        Paste,
        Copy,
        CloudArrowUp,
        Cloud,
        Bell,
        ThrashFill,
        ThrashCanFill,
        FileDownloadFill
    }
}
